server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource: 
    url: jdbc:h2:mem:family-space
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop